version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - .:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresqlcd
  app:
    container_name: jar
    image: jar
    depends_on:
      - db
    restart: always
    ports:
      - "8080:8080"